name: Deploy Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v7

    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: '3.14'  
        cache: 'pipenv'         # Cache venv

    - name: Install Pipenv
      run: pip install pipenv

    - name: Install Dependencies
      run: |
        pipenv install --deploy --categories="docs"

    - name: Auto-generate API Skeleton
      run: pipenv run sphinx-apidoc -o Docs/source/ ./Devices/ --force

    - name: Build HTML Documentation
      run: |
        cd docs
        pipenv run make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Docs/_build/html
